apiVersion: v1
kind: Pod
metadata: 
  name: kubernetes
spec: 
  hostNetwork: true
  volumes:
    - name: "etc-kubernetes"
      hostPath:
        path: "/etc/kubernetes"
    - name: "ssl-certs"
      hostPath:
        path: "/usr/share/ca-certificates"
    - name: "usr"
      hostPath:
        path: "/usr"
    - name: "lib64"
      hostPath:
        path: "/lib64"
  containers: 
    - name: "etcd"
      image: "kuar.io/etcd:2.0.13"
      args: 
        - "--data-dir=/var/lib/etcd"
        - "--advertise-client-urls=http://127.0.0.1:2379"
        - "--listen-client-urls=http://127.0.0.1:2379"
        - "--listen-peer-urls=http://127.0.0.1:2380"
        - "--name=etcd"
    - name: "kube-apiserver"
      image: "kuar.io/kube-apiserver:1.0.0"
      args: 
        - "--allow-privileged"
        - "--etcd-servers=http://127.0.0.1:2379"
        - "--insecure-bind-address=0.0.0.0"
        - "--service-cluster-ip-range=10.200.20.0/24"
        - "--v=2"
    - name: "kube-controller-manager"
      image: "kuar.io/kube-controller-manager:1.0.0"
      args: 
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-scheduler"
      image: "kuar.io/kube-scheduler:1.0.0"
      args:
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
    - name: "kube-proxy"
      image: "kuar.io/kube-proxy:1.0.0"
      args: 
        - "--master=http://127.0.0.1:8080"
        - "--v=2"
      securityContext: 
        privileged: true
      volumeMounts: 
        - mountPath: /etc/kubernetes
          name: "etc-kubernetes"
        - mountPath: /etc/ssl/certs
          name: "ssl-certs"
        - mountPath: /usr
          name: "usr"
        - mountPath: /lib64
          name: "lib64"
